## Load libraries

```{r}
library(data.table)
library(dplyr)
library(leaflet)
```

## Plot stops

```{r}
stops <- fread("./data/google_transit_M10/stops.txt")
stops <- filter(stops, substr(stops$stop_id, 0, 3) == 'par')
stops
```

```{r}
map <- c('A'='#F44', 'B1'='#44F', 'B2'='#55F', 'B4'='#66F')
color <- map[stops$zone_id]
color[is.na(color)] <- '#999'
color <- unname(color)
```

```{r}
leaflet() %>%
  addTiles() %>%
  addCircles(lat=stops$stop_lat, lng=stops$stop_lon, color=color)
```

## Plot trips

```{r}
datetime <- '2024-05-09 07:15:00'
datetime <- strptime(datetime, "%Y-%m-%d %H:%M:%S")

calendar_dates <- fread("./data/google_transit_M10/calendar_dates.txt")
exception <- calendar_dates[calendar_dates$date == strftime(datetime, "%Y%m%d")]

if (nrow(exception) == 0) {
  weekday <- as.numeric(strftime(datetime, '%w'))
  weekdays <- c(
    "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"
  )
  weekday <- weekdays[weekday]
  
  calendar <- fread("./data/google_transit_M10/calendar.txt")
  availability <- calendar %>% select(c(weekday, 'service_id'))
  
  if (sum(availability[,1]) != 1) {
    print("No service!")
  }
  
  service <- calendar[unlist(availability[,1]) == 1]$service_id
} else {
  service <- exception[1]$service_id
}

service
```

```{r}
trips <- fread("./data/google_transit_M10/trips.txt")
trips <- trips[!duplicated(trips$route_id), ]

routes <- fread("./data/google_transit_M10/routes.txt")
routes$route_color <- paste("#", routes$route_color, sep='')
routes$text_color <- paste("#", routes$text_color, sep='')

trips <- trips %>%
  merge(routes, by="route_id") %>%
  select(
    route_id, trip_id, route_color, route_text_color, route_long_name, direction_id
  )

frequencies <- fread("./data/google_transit_M10/frequencies.txt")
time <- strptime(strftime(datetime, "%H:%M:%S"), "%H:%M:%S")
frequencies <- frequencies %>% 
  filter( # TODO: Support hours > 24h
    strptime(frequencies$start_time, "%H:%M:%S") <= time&
    strptime(frequencies$end_time, "%H:%M:%S") > time
  )

if (nrow(frequencies) > 0) {
  trips <- trips %>% 
    merge(frequencies, by="trip_id") %>%
    select(-c(start_time, end_time, exact_times))
}

trips
```

```{r}
stop_times <- fread("./data/google_transit_M10/stop_times.txt")
stop_times <- stop_times %>%
  merge(stops, by="stop_id") %>%
  select(c(
    stop_id, trip_id, arrival_time, departure_time, stop_sequence, 
    stop_lat, stop_lon, zone_id,
  )) %>%
  merge(select(trips, c(trip_id, direction_id)), by="trip_id")
  
stop_times
```

```{r}

stop_times$departure_numeric <- 
  as.numeric(strptime(stop_times$departure_time, "%H:%M:%S"))

# TODO: support for hours >24h
stop_times[is.na(stop_times$departure_numeric)]$departure_numeric <- .Machine$integer.max

stop_times <- stop_times[order(stop_times$departure_numeric),]

x <- as.numeric(strptime(strftime(time, "%H:%M:%S"), "%H:%M:%S"))

index <- findInterval(x, stop_times$departure_numeric)

index <- index + 1

next_row <- stop_times[index, ]
next_row
```

```{r}
map <- leaflet() %>%
  addTiles() %>%
  addCircles(
    lat=stops$stop_lat,
    lng=stops$stop_lon,
    label=stops$stop_name,
    color=color,
    radius=20,
)

for (row in 1:nrow(trips)) {
  trip_stops <- stop_times %>% filter(stop_times$trip_id == trips[row]$trip_id)
  trip_stops <- trip_stops[order(trip_stops$stop_sequence),]
  map <- map %>% addPolylines(
    lat=trip_stops$stop_lat, 
    lng=trip_stops$stop_lon, 
    color=trips[row]$route_color, 
    label=trips[row]$route_long_name,
    weight=5, opacity=0.8,
  )
}

map
```

```{r}
draw_map <- function(folder, datetime, map) {
  stops <- fread(paste(folder, "/stops.txt", sep=''))
  stops <- filter(stops, substr(stops$stop_id, 0, 3) == 'par')
  
  color_map <- c('A'='#F44', 'B1'='#44F', 'B2'='#55F', 'B4'='#66F')
  color <- color_map[stops$zone_id]
  color[is.na(color)] <- '#999'
  color <- unname(color)
  
  datetime <- strptime(datetime, "%Y-%m-%d %H:%M:%S")
  
  calendar_dates <- fread(paste(folder, "/calendar_dates.txt", sep=''))
  exception <- calendar_dates[calendar_dates$date == strftime(datetime, "%Y%m%d")]
  
  if (nrow(exception) == 0) {
    weekday <- as.numeric(strftime(datetime, '%w'))
    weekdays <- c(
      "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"
    )
    weekday <- weekdays[weekday]
    
    calendar <- fread(paste(folder, "/calendar.txt", sep=''))
    availability <- calendar %>% select(c(weekday, 'service_id'))
    
    if (sum(availability[,1]) != 1) {
      print("No service!")
    }
    
    service <- calendar[unlist(availability[,1]) == 1]$service_id
  } else {
    service <- exception[1]$service_id
  }
  
  trips <- fread(paste(folder, "/trips.txt", sep=''))
  trips <- trips[!duplicated(trips$route_id), ]
  
  routes <- fread(paste(folder, "/routes.txt", sep=''))
  routes$route_color <- paste("#", routes$route_color, sep='')
  routes$text_color <- paste("#", routes$text_color, sep='')
  
  trips <- trips %>%
    merge(routes, by="route_id") %>%
    select(
      route_id, trip_id, route_color, route_text_color, route_long_name, direction_id
    )
  
  frequencies <- fread(paste(folder, "/frequencies.txt", sep=''))
  time <- strptime(strftime(datetime, "%H:%M:%S"), "%H:%M:%S")
  frequencies <- frequencies %>% 
    filter( # TODO: Support hours > 24h
      strptime(frequencies$start_time, "%H:%M:%S") <= time&
      strptime(frequencies$end_time, "%H:%M:%S") > time
    )
  
  if (nrow(frequencies) > 0) {
    trips <- trips %>% 
      merge(frequencies, by="trip_id") %>%
      select(-c(start_time, end_time, exact_times))
  }
  
  stop_times <- fread(paste(folder, "/stop_times.txt", sep=''))
  stop_times <- stop_times %>%
    merge(stops, by="stop_id") %>%
    select(c(
      stop_id, trip_id, arrival_time, departure_time, stop_sequence, 
      stop_lat, stop_lon, zone_id,
    )) %>%
    merge(select(trips, c(trip_id, direction_id)), by="trip_id")
  print(stops)
  map <- map %>%
    addTiles() %>%
    addCircles(
      lat=stops$stop_lat,
      lng=stops$stop_lon,
      label=stops$stop_name,
      color=color,
      radius=20,
    )
  
  for (row in 1:nrow(trips)) {
    trip_stops <- stop_times %>% filter(stop_times$trip_id == trips[row]$trip_id)
    trip_stops <- trip_stops[order(trip_stops$stop_sequence),]
    map <- map %>% addPolylines(
      lat=trip_stops$stop_lat, 
      lng=trip_stops$stop_lon, 
      color=trips[row]$route_color, 
      label=trips[row]$route_long_name,
      weight=5, opacity=0.8,
    )
  }
  
  return(map)
}
```

```{r}
draw_map('./data/google_transit_M5', '2024-05-09 10:15:00', leaflet())
```
